# [unstable]
# build-std = ["core"]
# build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-Z", "emit-stack-sizes",
    "-Z", "trap-unreachable=no",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "linker=flip-link",
    "-C", "link-arg=--nmagic",
]

# DISABLE --measure-stack if allocation is used
#         subtract size of heap from result!
# runner = "probe-run --measure-stack"
runner = "probe-run"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
PROBE_RUN_CHIP = "nrf52840_xxAA"

# optionally specify a probe if more than one is available
# probe-run --list-probes

# PROBE_RUN_PROBE = "1366:0101"         # segger jlink
# PROBE_RUN_PROBE = "0d28:0204"         # microbit
