[package]
authors = ["iot49"]
edition = "2021"
readme = "README.md"
name = "logger"
version = "0.1.0"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = ">=0.6,<0.8"
defmt = "0.3"
defmt-rtt = "0.4"
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6c8505697f198b95545f352f6a94af24276b128", features = ["defmt", "integrated-timers", "nightly"] }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6c8505697f198b95545f352f6a94af24276b128", features = ["defmt", "time-driver-rtc1", "gpiote", "nightly"], optional = true }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6c8505697f198b95545f352f6a94af24276b128", features = ["defmt", "time-driver-tim2", "nightly"], optional = true }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6c8505697f198b95545f352f6a94af24276b128", features = ["defmt", "nightly"] }
# nrf-softdevice = { version = "0.1.0", path = "../nrf-softdevice/nrf-softdevice", features = ["defmt", "nrf52840", "s140", "ble-peripheral", "ble-central", "critical-section-impl"] }
# nrf-softdevice-s140 = { version = "0.1.1", path = "../nrf-softdevice/nrf-softdevice-s140" }
embedded-hal = "0.2"
futures = { version = "0.3", default-features = false, features = ["async-await"] }
heapless = "0.7"
menu = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }
postcard = "1.0"
serde = { version = "1.0", default-features = false }

# common = { path = "../common", features = ["defmt"]}

[[bin]]
name = "logger"
test = false
bench = false
doc = false

[features]
default = [
    "particle-xenon"
]

particle-xenon = ["embassy-nrf/nrf52840", "_nrf"]
microbit-v2 = ["embassy-nrf/nrf52833", "_nrf"]

# Internal features - not intended for setting explicitly
_nrf = []
_stm32 = []

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
