[package]
name = "msgpack"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"

# rmp-futures = "0.3"

serde_json = "1.0"